<?php

namespace App\Sidecar;

use Hammerstone\Sidecar\LambdaFunction;
use Hammerstone\Sidecar\Runtime;

class StockTest extends LambdaFunction
{
    public function handler()
    {
        // TODO: Implement handler() method.
        return 'resources/lambdas/stockTest.lambda_handler';
    }

    public function package()
    {
        // TODO: Implement package() method.
        return [
            'resources/lambdas/stockTest.py',
            'resources/lambdas/PANDAS/zip.zip',
        ];
    }

    public function runtime()
    {
        // TODO: Change the autogenerated stub
        return Runtime::PYTHON_37;
    }
}
